// src/services/shipmentsMock.js
export const SHIPMENTS_MOCK = [
  {
    id: 2542,
    cliente: "Lucía Pigliacampi",
    destino: "Córdoba",
    comisionista: "Juan Pérez",
    fechaRetiro: "09/01/2026",
    fechaEntrega: "10/01/2026",
    origenDireccion: "Villa María, Darío Ramonda 1860",
    destinoDireccion: "Córdoba, Caseros 669",
    horarioRetiroAprox: "14:00 - 18:00",
    notas: "Tocar timbre. Paquete frágil.",
    ratingComisionista: 4.8,
    estado: "en_camino", // pendiente | en_retiro | en_camino | entregado | cancelado | demorado
    progreso: "en_camino", // solicitado | en_retiro | en_camino | entregado
    metodoPago: "mercadopago", // efectivo | transferencia | mercadopago
    precio: 4200,
    paquetes: [{ tipo: "Caja", alto: 30, ancho: 20, profundidad: 15, peso: 1200 }],
  },
  {
    id: 1026,
    cliente: "Pedro Gómez",
    destino: "Las Varillas",
    comisionista: "Juan Pérez",
    fechaRetiro: "09/01/2026",
    fechaEntrega: "10/01/2026",
    origenDireccion: "Villa María, Darío Ramonda 1860",
    destinoDireccion: "Las Varillas, Sarmiento 123",
    horarioRetiroAprox: "14:00 - 18:00",
    notas: "Llamar antes de pasar.",
    ratingComisionista: 4.8,
    estado: "pendiente",
    progreso: "solicitado",
    metodoPago: "efectivo",
    precio: 3900,
    paquetes: [{ tipo: "Caja", alto: 30, ancho: 20, profundidad: 15, peso: 1200 }],
  },
  {
    id: 1018,
    cliente: "John Lilki",
    destino: "Tío Pujio",
    comisionista: "Juan Pérez",
    fechaRetiro: "02/01/2026",
    fechaEntrega: "02/01/2026",
    origenDireccion: "Villa María, Catamarca 90",
    destinoDireccion: "Tío Pujio, Belgrano 100",
    horarioRetiroAprox: "09:00 - 11:00",
    notas: "Dejar en portería.",
    ratingComisionista: 4.8,
    estado: "entregado",
    progreso: "entregado",
    metodoPago: "transferencia",
    precio: 3100,
    paquetes: [{ tipo: "Caja", alto: 40, ancho: 35, profundidad: 30, peso: 3500 }],
  },
  {
    id: 1017,
    cliente: "John Lilki",
    destino: "Tío Pujio",
    comisionista: "Juan Pérez",
    fechaRetiro: "02/01/2026",
    fechaEntrega: "02/01/2026",
    origenDireccion: "Villa María, Catamarca 90",
    destinoDireccion: "Tío Pujio, Belgrano 100",
    horarioRetiroAprox: "09:00 - 11:00",
    notas: "",
    ratingComisionista: 4.8,
    estado: "cancelado",
    progreso: "solicitado",
    metodoPago: "efectivo",
    precio: 0,
    paquetes: [{ tipo: "Caja", alto: 20, ancho: 20, profundidad: 20, peso: 1000 }],
  },
  {
    id: 1020,
    cliente: "John Lilki",
    destino: "Tío Pujio",
    comisionista: "Juan Pérez",
    fechaRetiro: "02/01/2026",
    fechaEntrega: "02/01/2026",
    origenDireccion: "Villa María, Catamarca 90",
    destinoDireccion: "Tío Pujio, Belgrano 100",
    horarioRetiroAprox: "09:00 - 11:00",
    notas: "Tránsito pesado.",
    ratingComisionista: 4.8,
    estado: "demorado",
    progreso: "en_camino",
    metodoPago: "efectivo",
    precio: 3400,
    paquetes: [{ tipo: "Caja", alto: 20, ancho: 20, profundidad: 20, peso: 1000 }],
  },
];

export const COMISIONISTAS_MOCK = [
  { id: "c1", nombre: "Juan Pérez", rating: 4.8, precioEstimado: 4200, eta: "Hoy 14:00-18:00" },
  { id: "c2", nombre: "Carlos Sánchez", rating: 4.6, precioEstimado: 3800, eta: "Hoy 16:00-20:00" },
  { id: "c3", nombre: "Laura Díaz", rating: 4.9, precioEstimado: 4500, eta: "Mañana 09:00-12:00" },
];

export const DIRECCIONES_FRECUENTES_MOCK = [
  { id: "d1", alias: "Casa", direccion: "Darío Ramonda 1860", ciudad: "Villa María", provincia: "Córdoba", cp: "5900" },
  { id: "d2", alias: "Trabajo", direccion: "Av. España 123", ciudad: "Villa María", provincia: "Córdoba", cp: "5900" },
];
